defmodule Maraithon.Todos.ActivityEvent do
  @moduledoc """
  Durable audit-style activity generated by todo lifecycle changes.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id

  @event_types ~w(created deleted marked_done)
  @actor_types ~w(agent user)

  schema "todo_activity_events" do
    field :user_id, :string
    field :todo_id, :binary_id
    field :event_type, :string
    field :actor_type, :string
    field :actor_id, :string
    field :actor_label, :string
    field :todo_title, :string
    field :todo_source, :string
    field :metadata, :map, default: %{}
    field :occurred_at, :utc_datetime_usec

    timestamps(type: :utc_datetime_usec)
  end

  def changeset(activity_event, attrs) do
    activity_event
    |> cast(attrs, [
      :user_id,
      :todo_id,
      :event_type,
      :actor_type,
      :actor_id,
      :actor_label,
      :todo_title,
      :todo_source,
      :metadata,
      :occurred_at
    ])
    |> put_default_occurred_at()
    |> validate_required([:user_id, :event_type, :actor_type, :metadata, :occurred_at])
    |> validate_inclusion(:event_type, @event_types)
    |> validate_inclusion(:actor_type, @actor_types)
    |> validate_length(:actor_id, max: 320)
    |> validate_length(:actor_label, max: 255)
    |> validate_length(:todo_title, max: 240)
    |> validate_length(:todo_source, max: 100)
    |> validate_change(:metadata, fn :metadata, value ->
      if is_map(value), do: [], else: [metadata: "must be a map"]
    end)
    |> foreign_key_constraint(:user_id)
    |> foreign_key_constraint(:todo_id)
  end

  defp put_default_occurred_at(changeset) do
    case get_field(changeset, :occurred_at) do
      nil -> put_change(changeset, :occurred_at, DateTime.utc_now())
      _occurred_at -> changeset
    end
  end
end
