defmodule Maraithon.TelegramAssistant.RunReaper do
  @moduledoc """
  Periodically marks Telegram assistant runs that are stuck in `running` as
  `degraded`.

  A run only gets stuck if the process executing it died mid-flight — a node
  restart, a crash in the runner, or an OOM. Nothing else reclaims
  `telegram_assistant_runs` (unlike effects, background jobs, and scheduled
  jobs, which all have reclaimers), so without this, orphaned `running` rows
  accumulate forever and the durable run history can never be trusted.

  The timeout is deliberately generous — far longer than any real run — so this
  only ever catches genuinely orphaned runs, never slow ones.
  """

  use GenServer

  import Ecto.Query

  require Logger

  alias Maraithon.Repo
  alias Maraithon.Runtime.Config, as: RuntimeConfig
  alias Maraithon.Runtime.DbResilience
  alias Maraithon.TelegramAssistant.Run

  @default_poll_interval_ms 60_000
  # A real run finishes in well under a minute. Ten minutes without completion
  # means the executing process is gone and is never coming back.
  @default_stale_run_timeout_ms 600_000

  def start_link(opts) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  @impl true
  def init(_opts) do
    poll_interval_ms =
      RuntimeConfig.positive_integer(:run_reaper_poll_interval_ms, @default_poll_interval_ms)

    stale_timeout_ms =
      RuntimeConfig.positive_integer(:run_reaper_stale_timeout_ms, @default_stale_run_timeout_ms)

    schedule_poll(poll_interval_ms)

    {:ok, %{poll_interval_ms: poll_interval_ms, stale_timeout_ms: stale_timeout_ms}}
  end

  @impl true
  def handle_info(:poll, state) do
    _ =
      DbResilience.with_database("telegram run reaper", fn ->
        reap_stale_runs(state.stale_timeout_ms)
      end)

    schedule_poll(state.poll_interval_ms)
    {:noreply, state}
  end

  @doc """
  Mark every run still `running` whose `started_at` is older than
  `stale_timeout_ms` as `degraded`. Returns the number of runs reaped.

  Uses `update_all`, so `updated_at` is set explicitly (it is not autogenerated
  for bulk updates).
  """
  @spec reap_stale_runs(pos_integer()) :: non_neg_integer()
  def reap_stale_runs(stale_timeout_ms) when is_integer(stale_timeout_ms) do
    now = DateTime.utc_now()
    cutoff = DateTime.add(now, -stale_timeout_ms, :millisecond)

    {count, _} =
      Repo.update_all(
        from(r in Run,
          where: r.status == "running",
          where: r.started_at < ^cutoff
        ),
        set: [
          status: "degraded",
          error: "run_reaper_orphaned",
          finished_at: now,
          updated_at: now
        ]
      )

    if count > 0 do
      Logger.warning("Reaped #{count} orphaned Telegram assistant runs stuck in :running")
    end

    count
  end

  defp schedule_poll(interval_ms) do
    Process.send_after(self(), :poll, interval_ms)
  end
end
