defmodule Maraithon.TelegramAssistant.RunReaper do
  @moduledoc """
  Marks Telegram assistant runs that are stuck in `running` as `degraded`.

  `Maraithon.Runtime.RecurringJobs` supplies the durable cadence; this module
  owns only one bounded recovery pass.

  A run only gets stuck if the process executing it died mid-flight — a node
  restart, a crash in the runner, or an OOM. Nothing else reclaims
  `telegram_assistant_runs` (unlike effects, background jobs, and scheduled
  jobs, which all have reclaimers), so without this, orphaned `running` rows
  accumulate forever and the durable run history can never be trusted.

  The timeout is deliberately generous — far longer than any real run — so this
  only ever catches genuinely orphaned runs, never slow ones.
  """

  import Ecto.Query

  require Logger

  alias Maraithon.DurablePayload
  alias Maraithon.Repo
  alias Maraithon.Runtime.Config, as: RuntimeConfig
  alias Maraithon.Runtime.DbResilience
  alias Maraithon.TelegramAssistant.Run

  # A real run finishes in well under a minute. Ten minutes without completion
  # means the executing process is gone and is never coming back.
  @default_stale_run_timeout_ms 600_000

  def run_once do
    stale_timeout_ms =
      RuntimeConfig.positive_integer(:run_reaper_stale_timeout_ms, @default_stale_run_timeout_ms)

    case DbResilience.with_database("telegram run reaper", fn ->
           reap_stale_runs(stale_timeout_ms)
         end) do
      {:ok, count} -> %{reaped: count}
      {:error, reason} -> raise "telegram run reaper database failure: #{inspect(reason)}"
    end
  end

  @doc """
  Mark every run still `running` whose `started_at` is older than
  `stale_timeout_ms` as `degraded`. Returns the number of runs reaped.

  Uses `update_all`, so `updated_at` is set explicitly (it is not autogenerated
  for bulk updates).
  """
  @spec reap_stale_runs(pos_integer()) :: non_neg_integer()
  def reap_stale_runs(stale_timeout_ms) when is_integer(stale_timeout_ms) do
    now = DateTime.utc_now()
    cutoff = DateTime.add(now, -stale_timeout_ms, :millisecond)

    {:ok, {count, _}} =
      Repo.transaction(fn ->
        :ok = DurablePayload.require_current_mutation!()

        Repo.update_all(
          from(r in Run,
            where: r.status == "running",
            where: r.started_at < ^cutoff
          ),
          set: [
            status: "degraded",
            error: "run_reaper_orphaned",
            finished_at: now,
            updated_at: now
          ]
        )
      end)

    if count > 0 do
      Logger.warning("Reaped #{count} orphaned Telegram assistant runs stuck in :running")
    end

    count
  end
end
