defmodule Maraithon.Changelog do
  @moduledoc """
  Reads `priv/changelog.json` (generated by `mix changelog.generate`)
  and exposes the daily-grouped entries to the consumer-facing
  changelog surface.
  """

  @app :maraithon
  @path "changelog.json"

  @type entry :: %{
          required(:date) => Date.t(),
          required(:datetime) => DateTime.t(),
          required(:title) => String.t(),
          required(:sha) => String.t(),
          required(:summary) => String.t() | nil
        }

  @type day :: %{required(:date) => Date.t(), required(:entries) => [entry()]}

  @spec days() :: [day()]
  def days do
    case load() do
      %{"days" => days} when is_list(days) -> Enum.map(days, &normalize_day/1)
      _ -> []
    end
  end

  @spec generated_at() :: DateTime.t() | nil
  def generated_at do
    case load() do
      %{"generated_at" => iso} when is_binary(iso) ->
        case DateTime.from_iso8601(iso) do
          {:ok, dt, _} -> dt
          _ -> nil
        end

      _ ->
        nil
    end
  end

  defp load do
    @app
    |> :code.priv_dir()
    |> Path.join(@path)
    |> File.read()
    |> case do
      {:ok, body} -> Jason.decode!(body)
      _ -> %{}
    end
  end

  defp normalize_day(%{"date" => iso_date, "entries" => entries}) do
    %{
      date: parse_date(iso_date),
      entries: Enum.map(entries, &normalize_entry/1)
    }
  end

  defp normalize_entry(entry) do
    %{
      sha: Map.get(entry, "sha"),
      title: Map.get(entry, "title"),
      summary: nil_if_blank(Map.get(entry, "summary")),
      date: parse_date(Map.get(entry, "date")),
      datetime: parse_datetime(Map.get(entry, "datetime"))
    }
  end

  defp parse_date(nil), do: nil

  defp parse_date(iso) when is_binary(iso) do
    case Date.from_iso8601(iso) do
      {:ok, date} -> date
      _ -> nil
    end
  end

  defp parse_datetime(nil), do: nil

  defp parse_datetime(iso) when is_binary(iso) do
    case DateTime.from_iso8601(iso) do
      {:ok, dt, _} -> dt
      _ -> nil
    end
  end

  defp nil_if_blank(nil), do: nil
  defp nil_if_blank(""), do: nil
  defp nil_if_blank(value), do: value
end
